project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-0VWQVF21VS"
  title: "Ju-Chi Yu, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: tutorials.qmd
        text: Resources
    right:
      - icon: mortarboard-fill
        href: https://scholar.google.com.tw/citations?user=bkfSsy0AAAAJ&hl=en
      - icon: github
        href: https://github.com/juchiyu
      - icon: linkedin 
        href: https://www.linkedin.com/in/ju-chi-yu-83270695/
      - icon: bluesky
        href: https://bsky.app/profile/juchiyu.bsky.social
      - icon: twitter-x
        href: https://X.com/juchiyu
  page-footer: 
    center: "Ju-Chi Yu, Ph.D."
    right:
      - icon: mortarboard-fill
        href: https://scholar.google.com.tw/citations?user=bkfSsy0AAAAJ&hl=en
      - icon: github
        href: https://github.com/juchiyu
      - icon: linkedin 
        href: https://www.linkedin.com/in/ju-chi-yu-83270695/
      - icon: bluesky
        href: https://bsky.app/profile/juchiyu.bsky.social
      - icon: twitter-x 
        href: https://X.com/juchiyu

format:
  html:
    theme: sandstone
    css: css/bootstrap.min.css
    toc: true
    includes:
      in_header: 
        - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"

editor: visual
